include: package:very_good_analysis/analysis_options.3.0.2.yaml
analyzer:
  errors:
    # we use a custom line length
    lines_longer_than_80_chars: ignore
  exclude:
    - "**/*.gen.dart"
    - "**/*.g.dart"
