name: inventory_repository
description: Dart package which manages the inventory domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  api_client:
    path: ../api_client
  database_client:
    path: ../database_client
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  models:
    path: ../models
  storage_client:
    path: ../storage_client/storage_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  very_good_analysis: ^3.0.2
