/// Syncfusion calendar timezones
const calendarTimezones = [
  {'name': 'Samoa Standard Time', 'utc_difference': '-13:00'},
  {'name': 'Dateline Standard Time', 'utc_difference': '-12:00'},
  {'name': 'UTC-11', 'utc_difference': '-11:00'},
  {'name': 'Hawaiian Standard Time', 'utc_difference': '-10:00'},
  {'name': 'Alaskan Standard Time', 'utc_difference': '-09:00'},
  {'name': 'Pacific Standard Time', 'utc_difference': '-08:00'},
  {'name': 'Pacific Standard Time (Mexico)', 'utc_difference': '-08:00'},
  {'name': 'Mountain Standard Time', 'utc_difference': '-07:00'},
  {'name': 'Mountain Standard Time (Mexico)', 'utc_difference': '-07:00'},
  {'name': 'US Mountain Standard Time', 'utc_difference': '-07:00'},
  {'name': 'Canada Central Standard Time', 'utc_difference': '-06:00'},
  {'name': 'Central America Standard Time', 'utc_difference': '-06:00'},
  {'name': 'Central Standard Time', 'utc_difference': '-06:00'},
  {'name': 'Eastern Standard Time', 'utc_difference': '-05:00'},
  {'name': 'SA Pacific Standard Time', 'utc_difference': '-05:00'},
  {'name': 'US Eastern Standard Time', 'utc_difference': '-05:00'},
  {'name': 'Venezuela Standard Time', 'utc_difference': '-04:30'},
  {'name': 'Atlantic Standard Time', 'utc_difference': '-04:00'},
  {'name': 'Central Brazilian Standard Time', 'utc_difference': '-04:00'},
  {'name': 'Pacific SA Standard Time', 'utc_difference': '-04:00'},
  {'name': 'Paraguay Standard Time', 'utc_difference': '-04:00'},
  {'name': 'SA Western Standard Time', 'utc_difference': '-04:00'},
  {'name': 'Newfoundland Standard Time', 'utc_difference': '-03:30'},
  {'name': 'Bahia Standard Time', 'utc_difference': '-03:00'},
  {'name': 'Argentina Standard Time', 'utc_difference': '-03:00'},
  {'name': 'E. South America Standard Time', 'utc_difference': '-03:00'},
  {'name': 'Greenland Standard Time', 'utc_difference': '-03:00'},
  {'name': 'Montevideo Standard Time', 'utc_difference': '-03:00'},
  {'name': 'SA Eastern Standard Time', 'utc_difference': '-03:00'},
  {'name': 'UTC-02', 'utc_difference': '-02:00'},
  {'name': 'Azores Standard Time', 'utc_difference': '-01:00'},
  {'name': 'Cape Verde Standard Time', 'utc_difference': '-01:00'},
  {'name': 'GMT Standard Time', 'utc_difference': '0'},
  {'name': 'Greenwich Standard Time', 'utc_difference': '0'},
  {'name': 'Morocco Standard Time', 'utc_difference': '0'},
  {'name': 'UTC', 'utc_difference': '0'},
  {'name': 'Central Europe Standard Time', 'utc_difference': '+01:00'},
  {'name': 'Central European Standard Time', 'utc_difference': '+01:00'},
  {'name': 'Namibia Standard Time', 'utc_difference': '+01:00'},
  {'name': 'Romance Standard Time', 'utc_difference': '+01:00'},
  {'name': 'W. Central Africa Standard Time', 'utc_difference': '+01:00'},
  {'name': 'W. Europe Standard Time', 'utc_difference': '+01:00'},
  {'name': '', 'utc_difference': ''},
  {'name': 'Egypt Standard Time', 'utc_difference': '+02:00'},
  {'name': 'FLE Standard Time', 'utc_difference': '+02:00'},
  {'name': 'GTB Standard Time', 'utc_difference': '+02:00'},
  {'name': 'Israel Standard Time', 'utc_difference': '+02:00'},
  {'name': 'Libya Standard Time', 'utc_difference': '+02:00'},
  {'name': 'Middle East Standard Time', 'utc_difference': '+02:00'},
  {'name': 'South Africa Standard Time', 'utc_difference': '+02:00'},
  {'name': 'Syria Standard Time', 'utc_difference': '+02:00'},
  {'name': 'Turkey Standard Time', 'utc_difference': '+02:00'},
  {'name': 'Arab Standard Time', 'utc_difference': '+03:00'},
  {'name': 'Arabic Standard Time', 'utc_difference': '+03:00'},
  {'name': 'Belarus Standard Time', 'utc_difference': '+03:00'},
  {'name': 'E. Africa Standard Time', 'utc_difference': '+03:00'},
  {'name': 'Jordan Standard Time', 'utc_difference': '+03:00'},
  {'name': 'Kaliningrad Standard Time', 'utc_difference': '+03:00'},
  {'name': 'Iran Standard Time', 'utc_difference': '+03:30'},
  {'name': 'Arabian Standard Time', 'utc_difference': '+04:00'},
  {'name': 'Azerbaijan Standard Time', 'utc_difference': '+04:00'},
  {'name': 'Caucasus Standard Time', 'utc_difference': '+04:00'},
  {'name': 'Georgian Standard Time', 'utc_difference': '+04:00'},
  {'name': 'Mauritius Standard Time', 'utc_difference': '+04:00'},
  {'name': 'Russia Time Zone 3', 'utc_difference': '+04:00'},
  {'name': 'Russian Standard Time', 'utc_difference': '+04:00'},
  {'name': 'Afghanistan Standard Time', 'utc_difference': '+04:30'},
  {'name': 'Pakistan Standard Time', 'utc_difference': '+05:00'},
  {'name': 'West Asia Standard Time', 'utc_difference': '+05:00'},
  {'name': 'India Standard Time', 'utc_difference': '+05:30'},
  {'name': 'Sri Lanka Standard Time', 'utc_difference': '+05:30'},
  {'name': 'Nepal Standard Time', 'utc_difference': '+05:45'},
  {'name': 'Bangladesh Standard Time', 'utc_difference': '+06:00'},
  {'name': 'Central Asia Standard Time', 'utc_difference': '+06:00'},
  {'name': 'Ekaterinburg Standard Time', 'utc_difference': '+06:00'},
  {'name': 'Myanmar Standard Time', 'utc_difference': '+06:30'},
  {'name': 'SE Asia Standard Time', 'utc_difference': '+07:00'},
  {'name': 'N. Central Asia Standard Time', 'utc_difference': '+07:00'},
  {'name': 'China Standard Time', 'utc_difference': '+08:00'},
  {'name': 'North Asia Standard Time', 'utc_difference': '+08:00'},
  {'name': 'Singapore Standard Time', 'utc_difference': '+08:00'},
  {'name': 'Taipei Standard Time', 'utc_difference': '+08:00'},
  {'name': 'Ulaanbaatar Standard Time', 'utc_difference': '+08:00'},
  {'name': 'W. Australia Standard Time', 'utc_difference': '+08:00'},
  {'name': 'Korea Standard Time', 'utc_difference': '+09:00'},
  {'name': 'North Asia East Standard Time', 'utc_difference': '+09:00'},
  {'name': 'Tokyo Standard Time', 'utc_difference': '+09:00'},
  {'name': 'AUS Central Standard Time', 'utc_difference': '+09:30'},
  {'name': 'Cen. Australia Standard Time', 'utc_difference': '+09:30'},
  {'name': 'AUS Eastern Standard Time', 'utc_difference': '+10:00'},
  {'name': 'E. Australia Standard Time', 'utc_difference': '+10:00'},
  {'name': 'Tasmania Standard Time', 'utc_difference': '+10:00'},
  {'name': 'West Pacific Standard Time', 'utc_difference': '+10:00'},
  {'name': 'Yakutsk Standard Time', 'utc_difference': '+10:00'},
  {'name': 'Central Pacific Standard Time', 'utc_difference': '+11:00'},
  {'name': 'Russia Time Zone 10', 'utc_difference': '+11:00'},
  {'name': 'Vladivostok Standard Time', 'utc_difference': '+11:00'},
  {'name': 'Fiji Standard Time', 'utc_difference': '+12:00'},
  {'name': 'Magadan Standard Time', 'utc_difference': '+12:00'},
  {'name': 'New Zealand Standard Time', 'utc_difference': '+12:00'},
  {'name': 'Russia Time Zone 11', 'utc_difference': '+12:00'},
  {'name': 'UTC+12', 'utc_difference': '+12:00'},
  {'name': 'Tonga Standard Time', 'utc_difference': '+13:00'},
  {'name': 'Line Islands Standard Time', 'utc_difference': '+14:00'},
];
