name: firebase_analytics_client
description: Package which manages the firebase analytics domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analytics_client:
    path: ../analytics_client
  equatable: 2.0.5
  firebase_analytics: 10.9.0
  firebase_crashlytics: 3.4.20
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: 3.0.2
