name: authentication_client
description: An API-based implementation of the authentication client
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  api_client:
    path: ../api_client
  equatable: any
  models:
    path: ../models
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  very_good_analysis: ^3.0.2
