name: connectivity_repository
description: Flutter package which manages the connectivity domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  connectivity_plus: 6.0.3
  connectivity_plus_platform_interface: ^2.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  very_good_analysis: ^3.0.2
