name: user_tracing
description: A package wrapping Firebase Analytics to send verbose log data
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase_analytics: 10.9.0
  # firebase_core: 2.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.6
  mockito: 5.4.4
  very_good_analysis: 3.0.2
