name: secure_storage
description: A Key/Value Secure Storage Client
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  storage_client:
    path: ../storage_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4

  very_good_analysis: ^3.0.2
