name: app_ui
description: App UI Component Library
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: 3.0.0
  cached_network_image: 3.3.0
  cupertino_icons: 1.0.6
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_svg: 2.0.10+1
  intl: 0.19.0
  percent_indicator: 4.2.3
  scrollable_positioned_list: 0.3.8
  shimmer: 2.0.0
  toastification: ^2.0.0
  geolocator: 
  utils:
    path: ../utils
  vibration: 1.8.3
  user_tracing:
    path: ../user_tracing


dev_dependencies:
  build_runner: 2.4.8
  flutter_gen_runner: 5.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SF-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SF-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Heavy.otf
          weight: 800

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  lineLength: 80
  integrations:
    flutter_svg: true
