name: utils
description: Utils Library
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  models:
    path: ../models
  intl: 0.19.0
  flutter_image_compress: 2.1.0
  url_launcher: 6.3.0
  shared_preferences: 2.2.2

dev_dependencies:
  build_runner: 2.4.6
  flutter_gen_runner: 4.1.2+2
  flutter_test:
    sdk: flutter

flutter_gen:
  assets:
    outputs: 
      package_parameter_enabled: true
  lineLength: 80
