name: app_config_repository
description: Dart package which manages the app configuration domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: 2.0.5
  flutter:
    sdk: flutter
  launchdarkly_flutter_client_sdk: 4.6.0
  version: 3.0.2
  json_annotation: 4.8.1
  models:
    path: ../models
  package_info_plus: 4.2.0

dev_dependencies:
  build_runner:  2.4.6
  json_serializable: 6.7.0
