targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - cast_nullable_to_non_nullable
            - always_use_package_imports
      json_serializable:
        options:
          field_rename: snake
          create_to_json: true
          checked: true
          explicit_to_json: true
