name: database_client
description: Client communicating with the underlying database
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: 2.0.5
  file: 6.1.4
  flutter:
    sdk: flutter
  hive: 2.2.3
  hive_flutter: 
  intl: 0.19.0
  json_annotation: 4.8.1
  models:
    path: ../models
  rxdart: ^0.27.3
  storage_client: 
    path: ../storage_client/storage_client
  
  path_provider: 2.1.2
  path: ^1.8.1

dev_dependencies:
  build_runner: 2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: 6.7.0
  mocktail: 1.0.4
  hive_generator: 2.0.0
